# OpCode dictionary
OpCodes = {
    "ADD" : "0",
    "SUB" : "1",
    "AND" : "2",
    "IOR" : "3",
    "XOR" : "4",
    "SHR" : "5",
    "SHL" : "6",
    "CMP" : "7",
    "JMP" : "8",
    "BRZ" : "9",
    "BRN" : "A",
    "RES" : "B",
    "LOD" : "C",
    "STR" : "D",
    "SEL" : "E",
    "SEU" : "F",
}